create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  file_path text not null,
  created_at timestamptz not null default timezone('utc', now()),
  guest_name text
);
